export const env = {
  production: false,
  meses: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
  dias: ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"],
  apiUrl: 'http://localhost:41300/api',
  colores: [
    {"color": "Amarillo", "valor": "#FFFCCC"}, {"color": "Verde", "valor": "#C8EFD4"}, {"color": "Azul", "valor": "#C8EBFA"},
    {"color": "Purpura", "valor": "#D3D5F5"}, {"color": "Rosado", "valor": "#EDD3ED"}, {"color": "Esmeralda", "valor": "#C6FBF9"},
    {"color": "Lima", "valor": "#E9FAB6"}, {"color": "Crema", "valor": "#ECE4DB"}, {"color": "Gris", "valor": "#F2F2F2"},
    {"color": "Guindo", "valor": "#E7B9C0"}, {"color": "Rojo", "valor": "#FBCFD0"}, {"color": "Naranja", "valor": "#FFE5D4"},
  ],
  filtrarEstado: true,
  estado: 1,
  grupo: -1,
  textoBusqueda: "",
  dias_impares: ["lunes", "miercoles", "viernes", "domingo"],
  dias_pares: ["martes", "jueves", "sabado"],
  posY: 0,
  indexUsuario: -1,
  posYReporte: 0,
  indexResumenMarcacion: -1,
  categorias: ["Central", "Distritos", "Unidades", "Salud"],
  posCategoria: 0,
  posAdmCategoria: -1,
  sortColumn: "",
  sortDirection: ""
}
